#!/usr/bin/env python3
"""Generate C++ default-joint constants from the MuJoCo home keyframe."""

from __future__ import annotations

import argparse
import pathlib
import sys
import xml.etree.ElementTree as ET


JOINT_NAMES = (
  "FL_hip_joint",
  "FL_thigh_joint",
  "FL_calf_joint",
  "FR_hip_joint",
  "FR_thigh_joint",
  "FR_calf_joint",
  "RL_hip_joint",
  "RL_thigh_joint",
  "RL_calf_joint",
  "RR_hip_joint",
  "RR_thigh_joint",
  "RR_calf_joint",
)
FREE_JOINT_QPOS_SIZE = 7


def _numbers(key: ET.Element, attribute: str) -> list[float]:
  value = key.get(attribute)
  if value is None:
    raise ValueError(f"home keyframe is missing '{attribute}'")
  try:
    return [float(token) for token in value.split()]
  except ValueError as error:
    raise ValueError(f"home keyframe '{attribute}' contains a non-number") from error


def read_default_joint(scene_path: pathlib.Path) -> tuple[float, ...]:
  try:
    root = ET.parse(scene_path).getroot()
  except (OSError, ET.ParseError) as error:
    raise ValueError(f"cannot parse scene XML '{scene_path}': {error}") from error

  key = root.find("./keyframe/key[@name='home']")
  if key is None:
    raise ValueError("scene XML must define keyframe 'home'")

  qpos = _numbers(key, "qpos")
  ctrl = _numbers(key, "ctrl")
  expected_qpos_size = FREE_JOINT_QPOS_SIZE + len(JOINT_NAMES)
  if len(qpos) != expected_qpos_size:
    raise ValueError(
      f"home qpos must contain {expected_qpos_size} values, got {len(qpos)}"
    )
  if len(ctrl) != len(JOINT_NAMES):
    raise ValueError(
      f"home ctrl must contain {len(JOINT_NAMES)} values, got {len(ctrl)}"
    )

  joint_qpos = tuple(qpos[FREE_JOINT_QPOS_SIZE:])
  if joint_qpos != tuple(ctrl):
    raise ValueError("home qpos joint values and ctrl values must be identical")

  robot_path = scene_path.parent / "my_quadruped.xml"
  try:
    robot_root = ET.parse(robot_path).getroot()
  except (OSError, ET.ParseError) as error:
    raise ValueError(f"cannot parse robot XML '{robot_path}': {error}") from error
  model_joints = [
    element.get("name")
    for element in robot_root.iter("joint")
    if element.get("name") is not None
  ]
  expected_model_joints = ["float_base", *JOINT_NAMES]
  if model_joints != expected_model_joints:
    raise ValueError(
      "my_quadruped.xml joint order does not match the default-joint generator: "
      f"expected {expected_model_joints}, got {model_joints}"
    )

  return joint_qpos


def _format_float(value: float, suffix: str) -> str:
  formatted = format(value, ".9g")
  if "." not in formatted and "e" not in formatted.lower():
    formatted += ".0"
  return f"{formatted}{suffix}"


def render_cpp_header(values: tuple[float, ...]) -> str:
  float_values = ", ".join(_format_float(value, "F") for value in values)
  double_values = ", ".join(_format_float(value, "") for value in values)
  return f"""// Generated by tools/sync_default_joint.py. Do not edit.
#pragma once

#include <array>

namespace rl_quadruped
{{
inline constexpr std::array<float, {len(values)}> kDefaultJointPosition = {{{{
    {float_values}}}}};
inline constexpr std::array<double, {len(values)}> kDefaultJointPositionDouble = {{{{
    {double_values}}}}};
}}  // namespace rl_quadruped
"""


def main() -> int:
  parser = argparse.ArgumentParser()
  parser.add_argument("--scene", type=pathlib.Path, required=True)
  parser.add_argument("--cpp-output", type=pathlib.Path, required=True)
  args = parser.parse_args()

  try:
    values = read_default_joint(args.scene)
  except ValueError as error:
    print(f"sync_default_joint.py: error: {error}", file=sys.stderr)
    return 1

  args.cpp_output.parent.mkdir(parents=True, exist_ok=True)
  args.cpp_output.write_text(render_cpp_header(values), encoding="ascii")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
